---
require: rubocop-rspec

AllCops:
  DefaultFormatter: progress
  DisplayCopNames: true
  DisplayStyleGuide: false
  ExtraDetails: true
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false


Naming/FileName:
  Exclude:
    - lib/doorkeeper-jwt.rb

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
