---
require: rubocop-rspec

AllCops:
  DefaultFormatter: progress
  DisplayCopNames: true
  DisplayStyleGuide: false
  ExtraDetails: true
  TargetRubyVersion: 2.5

Metrics/LineLength:
  Exclude:
    - spec/**/*
  Max: 100

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - doorkeeper-jwt.gemspec

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/SymbolArray:
  MinSize: 3
Style/WordArray:
  MinSize: 3

Style/ClassAndModuleChildren:
  Exclude:
    - spec/**/*
Style/NumericPredicate:
  Enabled: false
Style/DoubleNegation:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/TrailingBlankLines:
  Enabled: true
Layout/DotPosition:
  EnforcedStyle: leading

Naming/FileName:
  Exclude:
    - lib/doorkeeper-jwt.rb

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
